apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
    
spec:
  ingressClassName: nginx
  rules:
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: gateway
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx #수정 필요 frontend
            port:
              number: 80
