source <(kubectl completion bash)
source <(kubeadm completion bash)
source <(kubectl completion bash)
source <(kubeadm completion bash)
source <(kubectl completion bash)
source <(kubeadm completion bash)
source <(kubectl completion bash)
source <(kubeadm completion bash)
